/* Generated by Bing(ChatGPT)

Prompt: Write a C program for me with a function called array_access_pattern that accepts a two dimensional array. Inside the function fill the array with 0s, and then use two loops to access that array with some pattern and insert in it a value of 1. Create a main function that calls the array_access_pattern passes it as array of size NxN where N is a macro with value 5. 

This program defines a function called `array_access_pattern` that accepts a two-dimensional array and its dimensions as arguments. Within the function, it first fills the array with `0`s. Then it uses two nested loops to access the array with a pattern where it inserts a value of `1` in every other cell. The `main` function calls the `array_access_pattern` function and passes it an array of size `NxN` where `N` is a macro with value `5`. Finally, the resulting array is printed to the console.
*/

#include <stdio.h>

#define N 5

void array_access_pattern(int rows, int cols, int arr[rows][cols]) {
    // Fill the array with 0s
    for (int i = 0; i < rows; i++) {
        for (int j = 0; j < cols; j++) {
            arr[i][j] = 0;
        }
    }

    // Use two loops to access the array with some pattern and insert in it a value of 1
    for (int i = 0; i < rows; i++) {
        for (int j = 0; j < cols; j++) {
            if ((i + j) % 2 == 0) {
                arr[i][j] = 1;
            }
        }
    }
}

int main() {
    int arr[N][N];
    array_access_pattern(N, N, arr);

    // Print the resulting array
    for (int i = 0; i < N; i++) {
        for (int j = 0; j < N; j++) {
            printf("%d ", arr[i][j]);
        }
        printf("\n");
    }

    return 0;
}



