# generated by configure / remove this line to disable regeneration
prefix="/home/users/shravank/projects/meliora2/Meliora/isl/isl_from_src/install"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/home/users/shravank/projects/meliora2/Meliora/isl/isl_from_src/isl-0.26/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="/home/users/shravank/projects/meliora2/Meliora/isl/isl_from_src/isl-0.26/./include"
package="isl"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "isl"
;; --help) pkg-config --help ; echo Buildscript Of "isl Library"
;; --modversion|--version) echo "0.26"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "" "-lisl"
       :
;; --cflags) echo -I${includedir} "-I./imath_wrap"
       :
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
